language: swift
osx_image: xcode9.2

script:
  - xcodebuild -workspace TMDbKit.xcworkspace -scheme BuildAll -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.2'
  - xcodebuild -workspace TMDbKit.xcworkspace -scheme UnitTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.2' test
