language: swift
osx_image: xcode9.2

before_install:
  - gem install jazzy

script: ./travis/build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - jazzy --swift-version 4.1 --source-directory ./src/TMDbKit --hide-documentation-coverage -a "Adam Borbas"
