ignore:
  - Pods/.*
  - **/UnitTests/.*
  - **/IntegrationTests/.*
  - docs/.*

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default: on
    patch:
      default: on
    changes:
      default: off

comment: false
